name: todo-app-automation
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.*"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    permissions:
      contents: read
    runs-on: [self-hosted, linux, x64]

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: lint with golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: run go mod download and go test
        run: |
          go mod download
          go test ./...
